### ISSUE TITLE
Add ReSharper 2019.1 support

### ISSUE THREAD

**Issue by OmiCron07** [Abc-Arbitrage/Abc.MoqComplete#1]

**Comment by lconstan** [comment]
Hello,
We will have a look on it when Resharper 2019.1 will not be in EAP anymore.

Thank you ! :)

**Comment by ltrzesniewski** [comment]
gogogogo :)

**Comment by lconstan** [comment]
Hi,
Version 1.2.2 is available and supports R# 2019.1

Thanks !
