### ISSUE TITLE
Add More description  in Readme

### ISSUE THREAD

**Issue by rampage64** [Abc-Arbitrage/Abc.MoqComplete#10]
Hi Folks,

It would be maybe nice to add an info in the Readme for which Versions of R# are supported and how to integrate it into R#? 

Good Work

Thanks!

**Comment by lconstan** [comment]
You can install it using the Resharper Extension Manager option (with visual studio 2019: **Extension** menu => **Resharper** => **ExtensionManager**) and look for the MoqComplete plugin.
https://www.jetbrains.com/help/resharper/Reference__Extension_Manager.html

I'm going to update the Readme.

Thanks !
