### ISSUE TITLE
Fill with Mock Local

### ISSUE THREAD

**Issue by Mike-E-angelo** [Abc-Arbitrage/Abc.MoqComplete#11]
I am exploring Moq and kicking the tires on the extension here.  Actually, I've had it installed _forever_ and am now _finally_ checking it out. 😁

Everything looks handy.  Thank you for taking the time to develop it.

The one thing I noticed is that the `Fill with Mocks` command seems to create outer instances that are placed in the containing class.

In my case, I would prefer these to be local to the test function.  

So instead of this:

```
	public sealed class Tests
	{
		Mock<IPromote> _previous;
		Mock<IPromoted> _promoted;

		[Fact]
		public async Task Verify()
		{
			_previous = new Mock<IPromote>();
			_promoted = new Mock<IPromoted>();
			var sut = new StateAwarePromote(_previous.Object, _promoted.Object);
		}
	}
```

It creates this:

```
	public sealed class Tests
	{
		[Fact]
		public async Task Verify()
		{
			var previous = new Mock<IPromote>();
			var promoted = new Mock<IPromoted>();
			var sut = new StateAwarePromote(previous.Object, promoted.Object);
		}
	}
```

Would it be possible to create a command that does this?

Thank you for any consideration and for making this cool extension!

**Comment by lconstan** [comment]
Yes indeed, 2 commands would be better.
The idea with the existing one is that you use it from the Setup method; that's why it creates fields.

I am going to create 2 commands, 1 for fields and 1 for local variables 👍

**Comment by Mike-E-angelo** [comment]
Very cool!  Thank you for your quick response and efforts. 🙏

**Comment by lconstan** [comment]
I'm closing this as it will be available in the next release of the plugin. Thanks !

**Comment by Mike-E-angelo** [comment]
Woohoo!  Thank you for being so quick to attend to this, @lconstan!

**Comment by Mike-E-angelo** [comment]
Beautimous!

![](https://i.imgur.com/xje7Fmo.gif)

Thanks again. 👍
