### ISSUE TITLE
MoqComplete is suggested for files without references to Moq

### ISSUE THREAD

**Issue by TCBroad** [Abc-Arbitrage/Abc.MoqComplete#12]
I do use Moq in the solution, but the suggestion balloon appears regardless of whether the file that's currently open contains a reference to Moq.

e.g.

![image](https://user-images.githubusercontent.com/1906419/91334953-a1f64180-e7c7-11ea-93ec-4a7957aa7f2a.png)

If this is by design, could you dial it back a bit so it only shows if the file uses moq, rather than the solution?

Cheers!

**Comment by ltrzesniewski** [comment]
That's a new feature of the IDE, so I don't think we can dial it down. See #9:

> Starting with Rider 2020.2 EAP2 there is a way to automatically suggest plugin, when it has **a certain reference**.

You'd need to ask JetBrains, but I don't think they could implement something more precise easily.

/cc @van800

**Comment by van800** [comment]
There was a problem in EAP, that even if plugin is installed it would still show notification. But that should not happen in release. So would either installing plugin or clicking "Ignore Unknown features" work?

**Comment by TCBroad** [comment]
> That's a new feature of the IDE, so I don't think we can dial it down. See #9:
> 
> > Starting with Rider 2020.2 EAP2 there is a way to automatically suggest plugin, when it has **a certain reference**.
> 
> You'd need to ask JetBrains, but I don't think they could implement something more precise easily.
> 
> /cc @van800

Ah fair enough, if it just targets references there's not really much you can do.

I've since had a look at the plugin and it seems quite useful so I guess the system worked - I'll just install it haha!

I'll close this issue, cheers for responding.
