### ISSUE TITLE
Support Rider EAP 203

### ISSUE THREAD

**Issue by rcdailey** [Abc-Arbitrage/Abc.MoqComplete#13]
I get a plugin warning that MoqComplete doesn't support builds over `202.*`. Can you support the EAP channel for Rider, which is at `203.*`?

**Comment by lconstan** [comment]
We don't support EAP in general because it requires time I don't have 😀 (as the sdk is changing)
I will do the update for 203 once its stable

**Comment by rcdailey** [comment]
Sadly I have to use the EAP version due to nuget issues in the stable channel. Thanks for your reply!
