### ISSUE TITLE
Plugin 'MoqComplete' (version 'null') is not compatible with the current version of the IDE

### ISSUE THREAD

**Issue by gustavomassa** [Abc-Arbitrage/Abc.MoqComplete#15]
![image](https://user-images.githubusercontent.com/16235598/100458659-e634fe80-30a2-11eb-96a2-c2e3b5517054.png)
![image](https://user-images.githubusercontent.com/16235598/100458743-0664bd80-30a3-11eb-8643-b6250a92fb1f.png)

`Plugin 'MoqComplete' (version 'null') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is RDCPPP-203.5981.17`

**Comment by lconstan** [comment]
This is an EAP version of Rider, we do not support it ([last version](https://www.jetbrains.com/rider/download/#section=windows) is 2020.2.4, [higher](https://www.jetbrains.com/rider/nextversion/) are EAP).
I will do the required change once its release.

**Comment by marcinsmialek** [comment]
@gustavomassa Meanwhile you can:

1. Download the latest zipped version from Releases folder
2. Bump version constraints in manifest as in this change https://github.com/Abc-Arbitrage/Abc.MoqComplete/commit/892b925fa16b04de34aa1acf4f67dc0817bda21f; keep plugin version intact
3. Add the altered zip to your Rider plugins (sprocket icon)
