### ISSUE TITLE
Plugin 'MoqComplete' (version '1.4.8') is not compatible. Requires build 211.*

### ISSUE THREAD

**Issue by inyutin-maxim** [Abc-Arbitrage/Abc.MoqComplete#24]
I install the plugin from the archive because he does not view in the plugin repo for Rider 2021.2.0
Rider throw next exception:
![image](https://user-images.githubusercontent.com/1781005/128142560-0689d675-62c6-4ba2-96a1-788c6322241c.png)

**Comment by lconstan** [comment]
Thanks for reporting the issue; 
I'm also unable to install the plugin locally (with or without the version constraint).
I've removed the version constraint and I'm going to upload a new version to the Jetbrains repository. Let's see how it goes when trying to install the plugin from there.
Commit for reference: 3f1cdb760128925a553e978b2e6481926595b453

**Comment by inyutin-maxim** [comment]
Nice, now it works for install from the archive :-)
