### ISSUE TITLE
Problems installing MoqComplete in Rider 2021.2

### ISSUE THREAD

**Issue by zetroot** [Abc-Arbitrage/Abc.MoqComplete#25]
Thank you a lot for your great plugin! It really helps typing!

After upgrade to 2021.2 i am unable to install MoqComplete. Rider finds it in marketplace (version 1.4.9) and i am able to install it, but after restart it is dropped and i do not see MoqComplete in installed plugins.

Rider build is 212.4746.113
Any ideas how to investigate?

**Comment by lconstan** [comment]
It seems to be an issue with Jetbrains Rider, I've contacted them here:
https://rider-support.jetbrains.com/hc/en-us/community/posts/4405250236050-Unable-to-install-MoqComplete-plugin-with-Rider

They have created an issue on their end. I suggest upvoting it so that it gets prioritized

**Comment by zetroot** [comment]
Upvoted&commented!

**Comment by inyutin-maxim** [comment]
> It seems to be an issue with Jetbrains Rider, I've contacted them here:
> https://rider-support.jetbrains.com/hc/en-us/community/posts/4405250236050-Unable-to-install-MoqComplete-plugin-with-Rider
> 
> They have created an issue on their end. I suggest upvoting it so that it gets prioritized

Hi, I think more important is the link to the tracker, vote for the task here: https://youtrack.jetbrains.com/issue/RIDER-66631

**Comment by Marat-Gumerov** [comment]
Is there any workaround? I've tried to install the plugin from disk, didn't help ((

**Comment by lconstan** [comment]
> Is there any workaround? I've tried to install the plugin from disk, didn't help ((

I haven't found any; downloading an older version of Rider may help: https://www.jetbrains.com/rider/download/other.html

**Comment by lconstan** [comment]
I'm going to trigger a new public release; in the meantime the plugin can be manually installed from the zip file [here](https://github.com/Abc-Arbitrage/Abc.MoqComplete/releases/tag/20210820.1)

Thanks @ForNeVeR  for the fix
