### ISSUE TITLE
ReSharper/Rider 2021.3

### ISSUE THREAD

**Issue by matkoch** [Abc-Arbitrage/Abc.MoqComplete#27]
Hi everyone!

This is just a reminder for the upcoming 2021.3 release. Please let me know if you need any help with the upgrade, or if you'd like us to take over upgrading.

All the best!

**Comment by lconstan** [comment]
Hello,
A PR to handle 2021.3 is welcome 😊 else we'll do the upgrade once the new version is released.

**Comment by lconstan** [comment]
@matkoch When installing the new version of the plugin (for 2021.3) on visual studio, I get this error

![image](https://user-images.githubusercontent.com/20269762/145361336-3675262f-0f39-46e5-96ec-0a86b05a4162.png)

Looking at the logs, I've seen that
``
09:30:10.282 ReSharperPlatformVs16_f382cc40MoqComplete: Error resolving type JetBrains.ReSharper.Feature.Services.CSharp.Analyses.Bulbs.ICSharpContextActionDataProvider from assembly “JetBrains.ReSharper.Feature.Services.CSharp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Feature.Services.CSharp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”. Could not find the type by its FQN. Is assembly qualification specified? True! Is it of our own assembly? True! Is looking into referenced assemblies allowed? False! Was the qualified referenced assembly encountered during lookup? False! Tried loading an implicitly-referenced assembly? False! Were following a forwarder exported type's assembly ref? No!
``

When testing the plugin afterward, the context actions are not working (we can't select them) but the completion is working fine.

What is strange is that all unit tests are working fine.

Should [those context action](https://github.com/Abc-Arbitrage/Abc.MoqComplete/blob/93f4eb45b8207e3c0386f5510a26eb7703beabd6/Abc.MoqComplete/Abc.MoqComplete/ContextActions/FillWithMock/FillParamWithMockContextAction.cs#L42) be modified?

I'm happy to share the logs files if needed

**Comment by matkoch** [comment]
The current main branch doesn't seem to use the `2021.3.0` version.

**Comment by lconstan** [comment]
The test was local. I've just pushed a new commit (cc0dc5c38ed39543265bd968c04f4e65f60b2a8e)

**Comment by matkoch** [comment]
Installation worked for me without any issues. Looks like it was compiled against the wrong version. Can you try cleaning everything?

**Comment by lconstan** [comment]
Indeed, it works from the build. I don't know what happened locally. I've pushed a new update. Sorry for the trouble!

**Comment by matkoch** [comment]
@lconstan if you have no objections I would suggest switching to a versioning scheme that reflects which ReSharper/Rider version is supported. I do this for all my plugins, and it makes it a bit easier for our support when dealing with raised issues. Like I said, just a suggestion, so you're absolutely free to do whatever works for you. Last but not least, of course, we very much appreciate your work on the plugin!

**Comment by matkoch** [comment]
One last thing: the compatibility seems to be incorrectly defined. The easiest to make it right is probably switching to our official plugin template, which takes care of all these things: https://github.com/jetbrains/resharper-rider-plugin

**Comment by lconstan** [comment]
Thanks; I'll have a look when time allows 😀
