### ISSUE TITLE
AutoComplete is broken again

### ISSUE THREAD

**Issue by maartenkools** [Abc-Arbitrage/Abc.MoqComplete#3]
**Additional info:**

- MoqComplete 1.2.6
- ReSharper 2019.2.2
- Visual Studio 16.2.3

**Comment by lconstan** [comment]
Hi,
Like the last time, the reason is that the plugin is not working yet for the last version of R# (2019.2.2).
We are aware if this and we are going to update it.

**Comment by lconstan** [comment]
Hi, 
The new version is now available. Thanks
