### ISSUE TITLE
Incompatible with R# 2023.1

### ISSUE THREAD

**Issue by ghost** [Abc-Arbitrage/Abc.MoqComplete#32]
![image](https://user-images.githubusercontent.com/30846057/233654505-78ae2040-a412-4946-befc-3c6dffe721ca.png)

**Comment by ltrzesniewski** [comment]
I submitted v2023.1.0.1 to the marketplace, it should be available in 2 business days.

**Comment by ghost** [comment]
Thank you very much. This tool is invaluable in coding with Moq.
