### ISSUE TITLE
A lot of exceptions in Rider 2023.2 EAP*

### ISSUE THREAD

**Issue by ArtManyak** [Abc-Arbitrage/Abc.MoqComplete#33]
Rider and R# 2023.2 contains breaking API change. Which produce a lot of exceptions when MoqComplete installed.
I will prepare fix for that issue.

```
--- EXCEPTION #1/2 [TypeLoadException]
Message = “Could not load type 'JetBrains.ReSharper.Psi.CSharp.Tree.IRegularParameterDeclaration' from assembly 'JetBrains.ReSharper.Psi.CSharp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325'.”
ExceptionPath = Root.InnerException
ClassName = System.TypeLoadException
HResult = COR_E_TYPELOAD=80131522
Source = Abc.MoqComplete.Rider
TypeLoadClassName = JetBrains.ReSharper.Psi.CSharp.Tree.IRegularParameterDeclaration
TypeLoadAssemblyName = “JetBrains.ReSharper.Psi.CSharp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
TypeLoadResourceID = -2146233054
StackTraceString = “
  at Abc.MoqComplete.CompletionProvider.MockVariableNameProvider.AddLookupItems(CSharpCodeCompletionContext context, IItemsCollector collector)
     at JetBrains.Util.Logging.Logger.CatchIgnoreException[TValue,TException](Func`1 F, TValue defaultValue) in CatchIgnoreException.il:line IL_0032 mvid B953
”
```

**Comment by ltrzesniewski** [comment]
Many thanks for the PR, that's _really_ helpful!

I'll release a new version soon, I just need to figure out how all of this works 😅 (the previous maintainer left and someone else needs to takes over).

**Comment by ltrzesniewski** [comment]
I've submitted updates to the marketplace.

**Comment by erri120** [comment]
![2023-06-02_14-59-45](https://github.com/Abc-Arbitrage/Abc.MoqComplete/assets/16577545/1d214206-3e85-4e11-8863-92d0d887d4e8)

https://plugins.jetbrains.com/plugin/12659-moqcomplete/versions

Not sure what's going on, but Rider will install `2023.1.0.1` instead of `2023.2.0.1` when running latest 2023.2 EAP2.

**Comment by ltrzesniewski** [comment]
Damn, I first submitted 2023.2.0.1 and *then* 2023.1.0.1 in order to fix #32. Looks like the JetBrains marketplace sorts extensions by date and not by version... 😕 

@ArtManyak should I re-upload a copy of 2023.2.0.1 as 2023.2.0.2, or is there a better approach?

**Comment by ltrzesniewski** [comment]
Ok, I noticed I can edit the compatibility ranges of existing versions, so I fixed it that way.

**Comment by erri120** [comment]
Works fine now :+1:
