### ISSUE TITLE
Version Missmatch

### ISSUE THREAD

**Issue by HJLuecking** [Abc-Arbitrage/Abc.MoqComplete#35]
I also got update notifications on a 2022.x version that a 2023.1.0.1 Version exists.
But the extension manager never did provide an update
After deinstall that plugin, that version can at least be seen.
But when i inspect the Github site there is no 2023.1.0.1 Version released,

**Comment by ltrzesniewski** [comment]
You can see all the available versions on the JetBrains Marketplace, along with their compatibility ranges:

- For ReSharper: https://plugins.jetbrains.com/plugin/11853-moqcomplete/versions
- For Rider: https://plugins.jetbrains.com/plugin/12659-moqcomplete/versions

I forgot to create releases on GitHub, I just added them for 2023.1.0.1 ad 2023.2.0.1.

Not sure why you got an update notification for a 2023 version on a 2022.x IDE, as their compatibility ranges shouldn't match.

**Comment by HJLuecking** [comment]
The IDE is VS 2019

**Comment by ltrzesniewski** [comment]
Ok, so you're using the ReSharper version of the plugin, and compatible versions depend on your ReSharper version.

If you're using a `2022.x` version of ReSharper, you can use the following releases of MoqComplete, depnding on the `x`:

- 2022.1: 2022.1.0.1
- 2022.2: 2022.2.0.1 or 2022.2.0.2
- 2022.3: 2022.3.0.2

No other version should be compatible.
