### ISSUE TITLE
A lot of exceptions in Rider 2023.3 EAP*

### ISSUE THREAD

**Issue by ArtManyak** [Abc-Arbitrage/Abc.MoqComplete#37]
Rider and R# contains breaking API change. Which produces a lot of exceptions when MoqComplete is installed.

```
--- EXCEPTION #1/2 [MissingMethodException]
Message = \“Method not found: 'JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.AspectLookupItems.BaseInfrastructure.LookupItem`1<JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.AspectLookupItems.Info.TextualInfo> JetBrains.ReSharper.Features.Intellisense.CodeCompletion.CSharp.CSharpLookupItemFactory.CreateKeywordLookupItem(JetBrains.ReSharper.Feature.Services.CSharp.CodeCompletion.Infrastructure.CSharpCodeCompletionContext, System.String, JetBrains.ReSharper.Psi.ExpectedTypes.TailType, JetBrains.UI.Icons.IconId)'.\”
ExceptionPath = Root.InnerException
ClassName = System.MissingMethodException
HResult = COR_E_MISSINGMETHOD=80131513
Source = Abc.MoqComplete.Rider

StackTraceString = “
  at Abc.MoqComplete.CompletionProvider.Callback.BaseCallbackMethodProvider`1.AddLookupItems(CSharpCodeCompletionContext context, IItemsCollector collector)
     at JetBrains.Util.Logging.Logger.CatchIgnoreException[TValue,TException](Func`1 F, TValue defaultValue) in CatchIgnoreException.il:line IL_0032 mvid 7B2E
\”
```

**Comment by ltrzesniewski** [comment]
Thanks for the info, the plugin will need an update indeed.

**Comment by ForNeVeR** [comment]
Please tell if you need help with the update.

**Comment by ltrzesniewski** [comment]
Thanks for offering help 🙂 

The fix was easy, and I just submitted an update.

**Comment by ltrzesniewski** [comment]
Actually I'll have a question @ForNeVeR 😅 

I got the following verification result:

![image](https://github.com/Abc-Arbitrage/Abc.MoqComplete/assets/7913492/0e32d12b-2475-4177-ad85-daa5c7342355)

It says *compatible*, but does the defect block the update? And can/should I just change the plugin id? Can I use the same id as for the ReSharper plugin?

**Comment by ForNeVeR** [comment]
@ltrzesniewski, for now this is a mere warning, and I am not aware of any plans to block further updates of plugins with "invalid" plugin ids. And changing of plugin id is tricky.

This validation was put in place relatively recently (definitely later than you published a plugin for the first time).

I'll open an internal discussion on this topic, thanks for notifying me. Abc.MoqComplete is not the only plugin that triggers this validation issue.

**Comment by ltrzesniewski** [comment]
Ok, I'll leave it as-is then. Thanks for the info! 🙂

**Comment by ForNeVeR** [comment]
I bring the answers: it is planned to disable the plugin id validation for the existing plugins. So, this won't be a problem for too long. Just ignore it for now.

**Comment by ltrzesniewski** [comment]
Makes sense. Thanks!
