### ISSUE TITLE
Supporting Moq.AutoMock

### ISSUE THREAD

**Issue by inyutin-maxim** [Abc-Arbitrage/Abc.MoqComplete#5]
I am using a library [Moq.AutoMocker](https://github.com/moq/Moq.AutoMocker). 
It allows you to make an IoC container from mock that resolves dependencies from mocks created using Moq
For example:
```cs
var mocker = new AutoMocker();
mocker.Use<IDriveTrain>(x => x.Accelerate(42) == true);

var car = mocker.CreateInstance<Car>();
car.Accelerate(42);

// This method verifies all mocks in the container
mocker.VerifyAll();
```

It would be great to expand the functionality to support this library 👍

**Comment by lconstan** [comment]
What kind of feature would you like Abc.MoqComplete to do in this case ?
I assume you want some code completion, can you please give examples ?

**Comment by inyutin-maxim** [comment]
mocker contains method Setup as in Moq
```cs
mocker.Setup<TSetupInstance,TReturnType>(x => x.SomeMethods(arg1, arg2)).Return(new TReturnType());
```
I want code completion for Setup methods.
Thanks for the cool plugin

**Comment by lconstan** [comment]
Currently the plugin is mainly focused on Moq itself; but why not expand its features! We would gladly accept accept a PR for this 👍
