### ISSUE TITLE
Automatically suggest plugin in Rider

### ISSUE THREAD

**Issue by van800** [Abc-Arbitrage/Abc.MoqComplete#9]
Starting with Rider 2020.2 EAP2 there is a way to automatically suggest plugin, when it has a certain reference.

If you want plugin to be automatically suggested, please contact JetBrains support and ask to add a plugin feature
`com.jetbrains.rider.solution.reference`
with value
`Moq`

Resulting dialog would look like this one: https://twitter.com/IvanShakhov/status/1270604533660626944

Ping me here in comments in case of any questions.

**Comment by ltrzesniewski** [comment]
That would be awesome! 😄
Thanks for the info.

The assembly name is `Moq` though. This plugin also handles `Moq.AutoMock` (#6) but it requires `Moq` anyway.

**Comment by lconstan** [comment]
Thanks, it would be very nice !
What's the best way to contact JetBrains support about this ? Using the community forum [here](https://rider-support.jetbrains.com/hc/en-us/community/topics/200410195-General-Discussion) ?

**Comment by van800** [comment]
Since I don't know what is the best way, I will just forward it directly. Thanks!

**Comment by van800** [comment]
Got it done for `https://plugins.jetbrains.com/plugin/12659-moqcomplete`

**Comment by van800** [comment]
Similar feature request for Re# https://youtrack.jetbrains.com/issue/RSRP-478043
Please vote, if you like it.

**Comment by ltrzesniewski** [comment]
Thanks! :+1:
